### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by bellstar** [ghdevelopers2305y/caption-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by UserTakato** [comment]
日置です。よろしくお願いします。

**Comment by daqivan4082** [comment]
テスト

**Comment by nana-sudo-p** [comment]
QUICK須藤です。よろしくお願いします！

**Comment by ryota915** [comment]
よろしくお願いします。

**Comment by rockblaze** [comment]
QUICK 宮城です～お願いします～

**Comment by TK-FDS** [comment]
FDS菊池です

**Comment by Tanaka555** [comment]
QUICK田中(美)です。よろしくお願いします

**Comment by takagiakiko2023** [comment]
高木です
すみません
遅れました

**Comment by MasaharuTakahashi0930** [comment]
QUICK高橋です

**Comment by t-takao-3298** [comment]
参加しました

**Comment by quick919hamada** [comment]
QUICKの濱田です。
